version: '3.8'

services:
  db:
    build: .
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "9000:80"
    networks:
      - mynetwork

networks:
  mynetwork: